### ISSUE TITLE
wei or way?

### ISSUE THREAD

**Issue by ElahiAli** [AlizadeAlireza/brownie_lottery#1]
Hi bro,
I was watching your code and I notice one thing, you have comment( ` in way` ) in file `contracts/Lottery.sol` line 32, here i think you meant wei, right?

**Comment by AlizadeAlireza** [comment]
hi,
yes that's right.
my purpose was wei.
wei : The smallest unit of Eth.

thanks for watching and  notices.

**Comment by ElahiAli** [comment]
> hi, yes that's right. my purpose was wei. wei : The smallest unit of Eth.
> 
> thanks for watching and  notices.

🙏
